version: 2.1

executors:
  python-executor:
    docker:
      - image: circleci/python:3.9  
    working_directory: ~/repo  
jobs:
  install_dependencies:
    executor: python-executor
    steps:
      - checkout 
      - run:
          name: Install dependencies
          command: |
            python -m venv venv  # Tworzymy wirtualne środowisko
            . venv/bin/activate  # Aktywujemy wirtualne środowisko
            pip install --upgrade pip  # Aktualizujemy pip
            pip install pytest  # Ręcznie instalujemy pytest

  run_tests:
    executor: python-executor
    steps:
      - checkout  
      - run:
          name: Run tests with pytest
          command: |
            . venv/bin/activate  # Aktywujemy środowisko wirtualne
            pytest --maxfail=1 --disable-warnings -q  # Uruchamiamy testy

workflows:
  version: 2
  test:
    jobs:
      - install_dependencies
      - run_tests:
          requires:
            - install_dependencies

